#端口号
server:
  port: 8099



  #数据源要更改为自己的
spring:
    # 环境开发/测试/线上 dev|test|prod
    profiles:
      active: dev
    # jackson时间格式化
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    http:
      multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.llf.springboot.model

#logback配置
logging:
  config: classpath:logback.xml
  level:
    com:
      llf:
        springboot: DEBUG
